### PR TITLE
federated_featurephenotypeassociaton_query and related test

### PR DESCRIPTION
**Pull request by ahwagner**
@ozanozisik implementation of `federated_featurephenotypeassociation_query`

### CODE REVIEW

**Comment by ahwagner** [comment]
Currently, requests to the 1kgenomes server do not yield any phenotype association sets, limiting development. Perhaps @bwalsh has some insight there.

The ensembl G2P services don't play nice with the `ga4gh-client` package, due to unexpected page size requests (issue created [here](https://github.com/ga4gh/ga4gh-client/issues/83)). 

I'll continue to review/contribute to this branch once one of these two avenues is open for continued testing.

**Comment by kozbo** [comment]
@ahwagner the G2P services should be up and running again on the 1kGenomes.ga4gh.org site. Give it a try and let me know if you have more problems with access.

**Comment by bwalsh** [comment]
@kozbo  thanks!

**Review by ozanozisik — APPROVED** [review]
Changing restricted lists to allowed lists is a good idea, I did not have an idea of how many sets we could reach so restricted lists seemed reasonable at that time.
Search methods in client classes are nice and neat.

**Comment by ahwagner** [comment]
@kozbo the cgd set is available again. Thanks!

**Pull request merged**
